package edu.zsc.ai.agent.subagent.contract;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Explorer SubAgent return structure.
 * <ul>
 *   <li>rawResponse — full LLM response text, consumed directly by MainAgent</li>
 *   <li>objects — structured relevant objects collected from getObjectDetail tool results</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SchemaSummary {
    /** Concise final summary generated by the model */
    private String summaryText;
    /** Full LLM response, consumed directly by MainAgent */
    private String rawResponse;
    /** Relevant objects collected from getObjectDetail tool results, not regex-parsed */
    private List<ExploreObject> objects;
}
