package edu.zsc.ai.agent.subagent.contract;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Planner SubAgent return structure.
 * The model is expected to return a single JSON object with summaryText, planSteps, sqlBlocks, and rawResponse.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SqlPlan {
    /** Concise final summary generated by the model */
    private String summaryText;
    /** Structured planning steps for UI display and MainAgent reasoning */
    private List<SqlPlanStep> planSteps;
    /** Structured SQL blocks for UI display and MainAgent reasoning */
    private List<SqlPlanBlock> sqlBlocks;
    /** Full LLM response, consumed directly by MainAgent */
    private String rawResponse;
}
